const BACKEND_URL = "https://flybnb.faiezwaseem.com/";
// const BACKEND_URL = "http://192.168.0.106/php/flybnb_api/";
const type = {
  REGISTER_USER : "REGISTER_USER",
  SIGNIN_USER : "SIGNIN_USER",
  CREATE_LISTING : "CREATE_LISTING",
  GET_LISTING : "GET_LISTING",
  SEARCH_LISTING : "SEARCH_LISTING",
  RESERVE_ROOM : "RESERVE_ROOM",
  MY_RESERVE_ROOM : "MY_RESERVE_ROOM",
  ADD_FAVOURITE : "ADD_FAVOURITE",
  MY_FAVOURITE : "MY_FAVOURITE"
}
const HOME_TYPES = {
  ROOM : "ROOM",
  TOWER : "TOWER",
  ISLAND : "ISLAND",
  TINY_HOME : "TINY_HOME",
  CONTAINER : "CONTAINER",
  DESIGN : "DESIGN",
  VIEW : "VIEW"
}
const ROOM_TYPES = {
  ENTIRE : "ENTIRE",
  SINGLE : "SINGLE",
  SHARED : "SHARED"
}
const GOOGLE_MAPS_API_KEY  = "";

export {
  BACKEND_URL,
  type,
  ROOM_TYPES,
  HOME_TYPES,
  GOOGLE_MAPS_API_KEY
}